import Head from "next/head";

export const Meta = () => (
    <Head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="Music Player" property="og:title" />
        <meta
            content="A simple music player created using Python and Tkinter to play music (or any audio) from YouTube or your computer! "
            property="og:description"
        />
        <meta content="https://musicplayer.isgood.dev/" property="og:url" />

        <meta content="./musical_note.ico" property="og:image" />
        <meta content="#f24646" data-react-helmet="true" name="theme-color" />
        <link rel="icon" href="/musical_note.ico" />
    </Head>
);
